In [3]:
# Задача 1 от 20_03_2023 (I вариант)

n = int(input()) 
k = int(input())  
x = k // n
y = k % n
print(x)
print(y)

3
14
4
2


In [ ]:
# Задача 1 от 20_03_2023 (II вариант)
     
def share_bread(n, k):
    x = k // n   # возвращает неполное частное от деления в виде целого числа
    y = k % n    # % - оператор выводит остаток от деления
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(n = 3, k = 14) == (4, 2)

In [6]:
#Задача 2 (вариант I)
year = int(input())
if year % 4 == 0 and year % 100 != 0 or year % 400 == 0:
    print("YOU SHALL PASS")
else:
    print("YOU SHALL NOT PASS")

5
YOU SHALL NOT PASS


In [4]:
# Задача 2 (вариант II)
def leap_year(year): 
    if (year % 4) == 0: 
        if (year % 100) == 0: 
            if (year % 400) == 0: 
                return "YOU SHALL PASS"
            else: 
                return "YOU SHALL NOT PASS"
        else: 
             return "YOU SHALL PASS"
    else: 
        return "YOU SHALL NOT PASS" 

assert leap_year(5) == "YOU SHALL NOT PASS"

In [5]:
#Задача 3 (вариант I)
a, b, c = int(input()), int(input()), int(input()) 
p = (a + b + c) / 2 
s = (p * (p - a) * (p - b) * (p - c)) ** 0.5 
print(s)

3
4
5
6.0


In [7]:
#Задача 3 (вариант II)
def amulet_area(a, b, c):
    #a, b, c = int(input()), int(input()), int(input()) 
    p = (a + b + c) / 2 
    s = (p * (p - a) * (p - b) * (p - c)) ** 0.5 
    return s

assert amulet_area(3, 4, 5) == 6

In [19]:
#Задача 4 (I вариант - через мат.формулы)

import numpy as np

def cal_euclidean(a, b): 
    distance1 = np.sqrt(np.sum(np.square(a-b)))
    return distance1

def cal_manhattan(a, b):    
    distance2 = np.sum(np.abs(a - b))
    return distance2

def cal_cosine(a, b):    
    distance3 = np.dot(a,b)/(np.linalg.norm(a)*(np.linalg.norm(b))) 
    return distance3

In [20]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

26.362852652928137
57
-0.0451312066164497


In [21]:
#Задача 4 (II вариант - через функцию np.linalg.norm())

import numpy as np

def cal_euclidean(a, b): 
    distance1 = np.linalg.norm(a - b)
    return distance1

def cal_manhattan(a, b):    
    distance2 = np.linalg.norm(a-b,ord=1)
    return distance2

def cal_cosine(a, b):    
    distance3 = np.dot(a,b)/(np.linalg.norm(a)*(np.linalg.norm(b))) 
    return distance3

In [17]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

22.045407685048602
22.045407685048602
0.2522435388362116


In [10]:
#Задача 5.1
import numpy as np
my_array = np.random.rand(100)

# Находим max элемент массива и заменяем его 1
my_array[np.where(my_array == my_array.max())] = 1

# Находим min элемент массива и заменяем его 0
my_array[np.where(my_array == my_array.min())] = 0

print("Наибольшее число:", np.max(my_array), "Наименьшее число:",np.min(my_array))
print(my_array)


Наибольшее число: 1.0 Наименьшее число: 0.0
[0.81857048 0.58018394 0.74721422 0.0866675  0.47053374 0.62211647
 0.97924155 0.51801878 0.75907614 0.9000502  0.86719696 0.32047031
 0.44880534 0.3733723  0.90200499 0.70087008 0.49416385 1.
 0.68320533 0.96614712 0.56060937 0.17840081 0.20951962 0.66956765
 0.21309011 0.95092394 0.05225372 0.13791931 0.33352573 0.36680129
 0.491167   0.44317074 0.33556889 0.42104336 0.41716131 0.16151237
 0.49823227 0.57521588 0.33827742 0.79749364 0.50791194 0.02380672
 0.50837322 0.38139279 0.01955524 0.30235936 0.25215882 0.9876022
 0.44394554 0.75993045 0.04520238 0.02990122 0.43181657 0.96041017
 0.77151462 0.2718761  0.78470171 0.22248741 0.4950831  0.11209014
 0.14685616 0.40460269 0.20574267 0.27500409 0.37875077 0.31737516
 0.3960418  0.76602641 0.8676071  0.32878169 0.37225644 0.25832913
 0.36621445 0.20663194 0.57768746 0.64295431 0.43685035 0.68362063
 0.08406103 0.36108803 0.13341377 0.63958689 0.2192511  0.43715021
 0.22630994 0.54222933 0.31

In [11]:
#Задача 5.2 (6)
import numpy as np
my_array = np.random.randint(0,50,(5,6))
# нам нужен столбец, поэтому перебираем сверху вниз и кладем axis = 0
selected_column = my_array[:, np.argmax(my_array.max(axis = 0))]
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Shape:  (5, 6)
Array
[[21 29 28 21  4  0]
 [43  5 21  2 19 36]
 [ 1 14 28 46 35  8]
 [21 15 16 25 42 42]
 [29 45  7 46 20  4]]
[21  2 46 25 46]


In [32]:
#Задача 5.3 (7)
def get_unique_rows(X):
    # преобразовываем каждую строку (список) в кортеж. [Помещаем все строки(список) в набор,
    # потому что набор содержит уникальные значения.
    # Поскольку list является нехешируемым типом для set, потому что он изменяемый,
    # поэтому сначала мы преобразуем каждую строку (список) в кортеж, а затем помещаем весь кортеж в set]
    # сопоставляем функцию кортежа с каждой строкой входной матрицы
    X = map(tuple, X)
 
    # Результирующий набор будет содержать только кортежи с уникальными значениями (строками)
    # помещаем все строки в set
    result = set(X)
 
    # печатаем все уникальные строки
    for row in list(result):
        print (row)
    return 

In [33]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[4 4 4]
 [5 4 5]
 [5 5 5]
 [4 4 5]
 [5 4 4]
 [5 4 4]
 [5 5 5]
 [4 4 5]
 [4 4 5]
 [4 5 4]]


In [34]:
get_unique_rows(X)

(5, 4, 5)
(5, 5, 5)
(4, 5, 4)
(4, 4, 5)
(5, 4, 4)
(4, 4, 4)
